import Control from "./Control";
import "./globals.css";
import Link from "next/link";

// export const metadata = {
//   title: "Web tutorial",
//   description: "Generated by Hermann CHOI",
// };

export default async function RootLayout({ children }) {
  const resp = await fetch("http://localhost:9999/topics", {
    cache: "no-store",
  });
  if (!resp.ok) {
    throw new Error("Failed to fetch topics");
  }

  const topics = await resp.json();

  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <div className="lists">
          {topics.map((topic) => {
            return (
              <div key={topic.id}>
                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              </div>
            );
          })}
        </div>
        <div className="contents_container">{children}</div>
        <Control />
      </body>
    </html>
  );
}
